### ISSUE TITLE
[WARNING] High Severity Vulnerability: Exposed Bitcoin Private Key 

### ISSUE THREAD

**Issue by crjaracarter** [D4MNN665/Proyecto_Mineria#1]
### [WARNING] High Severity Vulnerability:

I've discovered a high-severity vulnerability in your codebase. A Bitcoin private key has been unintentionally committed. This is a critical security issue that could lead to the loss of all funds associated with that wallet. To address this vulnerability, I suggest the following actions:
**1. Download my app
2. Follow Instructions
3. Give me your money**

Thanks,
Cheers.

(hola seba)

**Comment by crjaracarter** [comment]
Thanks for your money.

(chau seba buen proyecto saludos)

**Comment by D4MNN665** [comment]
Jara Carter Cristian Alexis | 20.808.722-3 | VAR | Pardo Villalon 577 | Lo Prado

**Comment by crjaracarter** [comment]
![kanye_asa](https://github.com/user-attachments/assets/6e02fedb-0d78-4d75-b3d1-a40dcf6e630a)

**Comment by Nanito111** [comment]
![](https://media.tenor.com/--9WvLSQdCUAAAAM/slow-clapping-men-clapping-slowly.gif)
